### ISSUE TITLE
Can not import Cisco Meraki QR code

### ISSUE THREAD

**Issue by ThatGuyJon** [timokoessler/2FAGuard#14]
### What happened?

Was trying to add QR code provided by Cisco Meraki account. It said it was a Duo Security 2FA which is most likely why it wasnt accepting but figured id report to see if this is something that could be added.

### Provide the error message / stack trace

![image](https://github.com/timokoessler/2FAGuard/assets/54686106/c24d46a4-9b69-4e6a-90d9-44d90fc71252)

### What version of Windows are you using?

Windows 11

### What version of the app are you using?

1.2.0.0

**Comment by timokoessler** [comment]
Thanks for reporting. Can you perhaps provide me an anonymised version of the QR code content?

**Comment by ThatGuyJon** [comment]
otpauth://totp/jonathan%40*******.com%2FMeraki?secret=********

Im not sure if this is the information your looking for, but this is what the QR code reports when i scan it.

Redacted email and secret ofc.

**Comment by timokoessler** [comment]
The issue is that the url contains %2F (a url encoded / ) instead of a colon (:) as a separator between account name and issuer. This does not follow the [standard uri format.](https://github.com/google/google-authenticator/wiki/Key-Uri-Format). I will implement a fix that will allow such type of uris.
