### ISSUE TITLE
Bug: Can't reset the app

### ISSUE THREAD

**Issue by Unleash123** [timokoessler/2FAGuard#35]
### What happened?

Hitting "Reset app > Delete all tokens and settings" prompts an error.

### Provide the error message / stack trace

![image](https://github.com/user-attachments/assets/65204f88-7394-441f-bd5b-92b0454f4cdb)

### What version of Windows are you using?

Windows 11 Home 23H2

### What version of the app are you using?

1.5.0.0

**Comment by timokoessler** [comment]
Thank you for reporting this issue. It only happens if Windows Hello is not set up. If you want to delete all your data before the fix is released and you cannot enable Windows Hello, follow these steps:

- Installer: Delete the folder `C:\Users\%username%\AppData\Local\2FAGuard`
- Portable edition: Delete the apps data folder that is located in the same directory as the exe
- Microsoft Store App: Delete the data of this app in the Windows Settings

**Comment by Unleash123** [comment]
Thank you for the guidelines.
Handy as I was importing two different sorts of files and wanted to compare. All good now.

**Comment by timokoessler** [comment]
Fixed in version 1.5.1. 🚀
