### ISSUE TITLE
[Feature Request]: Export feature compatible with other 2FA apps

### ISSUE THREAD

**Issue by Unleash123** [timokoessler/2FAGuard#36]
### What is your idea?

I used to be an Authy user. That app wouldn't let us export the data at all, until someone wrote a script to solve this. 
I would like to avoid this situation once more, should anything happen to 2FAGuard.
At the moment, it seems the only available option to export is 2FAGuard compatible only.
I'd feel safer if there was the possibility to export to a file that can be used in most if not all other 2FA apps.

**Comment by timokoessler** [comment]
I had the same problem with Authy a few years ago. That's why it's possible to export all tokens as a _generic uri list_, which is supported by many different applications. You can also export your tokens as an encrypted [Authenticator Pro](https://authenticatorpro.jmh.me) backup. To export individual tokens, you can right-click on a token card and click View QR Code.
If you would like to see additional export options, feel free to create a new issue.
