### ISSUE TITLE
Allow system-wide installation for all users

### ISSUE THREAD

**Issue by ThatGuyJon** [timokoessler/2FAGuard#7]
### What is your idea?

Add option to install for all users but have the liteDB store in users individual appdata as it currently does.

**Comment by timokoessler** [comment]
I will change the installer so that system-wide installations with admin rights are possible, but still the standard installation does not require admin rights. But I have to check for possible problems with the update process.

https://jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequiredoverridesallowed

**Comment by ThatGuyJon** [comment]
Its mainly so that it can be deployed on the system and anyone who logs into the PC will have access to the software, and be able to have there own configuration.

Used for multi user devices / Terminal servers
